name: Run test suite of WebApp

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          MYSQL_DATABASE: csye6225
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create application-test.properties for tests
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/application-test.properties << EOL
          spring.application.name=cloud
          spring.datasource.url=jdbc:mysql://localhost:3306/csye6225?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          spring.datasource.username=${{ secrets.DB_USERNAME }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}
          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.jpa.show-sql=true
          spring.jpa.hibernate.ddl-auto=update
          spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
          spring.datasource.hikari.connection-timeout=3000
          spring.datasource.hikari.minimum-idle=5
          spring.datasource.hikari.maximum-pool-size=5
          spring.datasource.hikari.idle-timeout=300000
          EOL

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run tests
        env:
          DB_URL: jdbc:mysql://localhost:3306/csye6225?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SPRING_PROFILES_ACTIVE: test
        run: mvn test
