name: Packer Format and Validation Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Application Artifact
        run: mvn clean package -DskipTests

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Initialize Packer Plugins
        run: packer init packer/

      - name: Check Packer formatting
        run: packer fmt -check -diff packer/

      - name: Validate Packer template
        run: packer validate packer/